### ISSUE TITLE
[Bug] Allways home

### ISSUE THREAD

**Issue by bernardovalente** [Vaskivskyi/ha-asusrouter#221]
### The problem

Hi,

I really appreciate the work you've done with this integration.

It seems that for me none of the device_trackers are updating its status, the state remains at home at all times, no matter if connected do wifi or not, even when the integration is reloaded or the system rebooted. I don't think there's nothing in the core logs that's related to this integration and I'm not really sure how to debug this behaviour.

Cheers

### Your device model

RT-AX56_XD4

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49599-g8352df7

### Integration version with the issue

0.80

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

 Home Assistant 2022.9.1 Supervisor 2022.08.6 Operating System 8.5 Frontend 20220907.0 - latest

**Comment by Vaskivskyi** [comment]
Hello, @bernardovalente,

Thanks for your feedback! 👍🏻 

I am sorry, that the integration does not work well for you.

Could you please check whether the `sensor.{devicename}_connected_devices` is showing the correct number of connected devices? Does it update or is it also stuck as well as device trackers?
- Just turn WiFi off / on for some mobile device - that would be the fastest method to check. You might also change the sensors update speed in the integration configurations (Click Configure - Time constants - set `interval to update entities` to e.g. 10 seconds and `consider device at home` to 7 e.g. seconds). Don't forget to restart the integration after changing the configurations (Menu (3 dots) - Reload - Wait for ~30 seconds, while HA reloads the integration).

Let me know what you find, so we can proceed with the troubleshooting.

**Comment by bernardovalente** [comment]
Thanks for the response.

So the `sensor.{devicename}_connected_devices` is also stuck at fixed number not matching to the actual number of connected devices neither does. To tey and fix I changed the time constraints, reloaded the integration but the change in state is still not detected in HA. A removal/install of the integration also didn't work.

Forgot to say that other sensors like dw/up speed work fine.

Thank you for you time

**Comment by bernardovalente** [comment]
It seems that a couple of error popped on the logs that might help diagnose

_This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/asusrouter/bridge.py:139
Integration: ASUS Router (documentation, issues)
First occurred: 11:19:47 (1 occurrences)
Last logged: 11:19:47

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 179, in async_request
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 112, in async_run_command
    result = await self.async_request(command, endpoint, self._headers)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 255, in async_request
    raise AsusRouterConnectionTimeoutError()
asusrouter.error.AsusRouterConnectionTimeoutError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/asusrouter/bridge.py", line 137, in async_get_connected_devices
    api_devices = await self._api.async_get_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 740, in async_get_devices
    await self.async_monitor_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 594, in async_monitor_devices
    data = await self.async_hook(AR_HOOK_DEVICES)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 305, in async_hook
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 300, in async_hook
    result = await self.connection.async_run_command(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 118, in async_run_command
    await self.async_connect()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 179, in async_request
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/asusrouter/router.py", line 397, in update_all
    await self.update_devices()
  File "/config/custom_components/asusrouter/router.py", line 405, in update_devices
    api_devices = await self._api.async_get_connected_devices()
  File "/config/custom_components/asusrouter/bridge.py", line 139, in async_get_connected_devices
    raise UpdateFailed(ex) from ex
homeassistant.helpers.update_coordinator.UpdateFailed: [Errno 104] Connection reset by peer
_

And this one:

_This error originated from a custom integration.

Logger: custom_components.asusrouter.router
Source: helpers/update_coordinator.py:151
Integration: ASUS Router (documentation, issues)
First occurred: 11:19:47 (3 occurrences)
Last logged: 11:19:47

Error fetching vpn data: [Errno 104] Connection reset by peer
Error fetching wan data: [Errno 104] Connection reset by peer
Error fetching wlan data: [Errno 104] Connection reset by peer_

Thanks, really appreciate your help.

**Comment by bernardovalente** [comment]
Hi 
`This error originated from a custom integration.

Logger: custom_components.asusrouter.router
Source: helpers/update_coordinator.py:151
Integration: ASUS Router (documentation, issues)
First occurred: 11:19:47 (3 occurrences)
Last logged: 11:19:47

Error fetching vpn data: [Errno 104] Connection reset by peer
Error fetching wan data: [Errno 104] Connection reset by peer
Error fetching wlan data: [Errno 104] Connection reset by peer

**Comment by Vaskivskyi** [comment]
Hello,

Sorry for the delay. I wanted to let you know, that I am still working on this issue.

It seems like this problem is reproducible in several cases on different device types, but I was not yet able to find anything in common. I will let you know about the progress or if I will need some more information.

**Comment by bernardovalente** [comment]
No worries. To add to the troubleshooting, while I was updating and messing with unrelated device and network configs, the integration seemed to started to update the device tracker's state and connected devices list but with a delay of hours on the list, still haven't timed the devices tracker update time.

Thank you

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.8.1, which is already available through HACS. The "Connection reset by peer" problem should now be solved.

We'll see, whether this helped with the device trackers issue as well.

**Comment by bernardovalente** [comment]
Hi, thanks for the update.

It seems that some issues still remain, updated to lastest version and the different entities were updating within the established time constraint but a few hours later an error popped and the device trackers and connected list are no longer updating.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/asusrouter/bridge.py:139
Integration: ASUS Router (documentation, issues)
First occurred: 00:21:05 (1 occurrences)
Last logged: 00:21:05

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 179, in async_request
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/asusrouter/bridge.py", line 137, in async_get_connected_devices
    api_devices = await self._api.async_get_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 742, in async_get_devices
    await self.async_monitor_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 596, in async_monitor_devices
    data = await self.async_hook(AR_HOOK_DEVICES)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 307, in async_hook
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 302, in async_hook
    result = await self.connection.async_run_command(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 118, in async_run_command
    await self.async_connect()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 266, in async_request
    raise AsusRouterConnectionError(str(ex)) from ex
asusrouter.error.AsusRouterConnectionError: ('[Errno 104] Connection reset by peer', None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/asusrouter/router.py", line 397, in update_all
    await self.update_devices()
  File "/config/custom_components/asusrouter/router.py", line 405, in update_devices
    api_devices = await self._api.async_get_connected_devices()
  File "/config/custom_components/asusrouter/bridge.py", line 139, in async_get_connected_devices
    raise UpdateFailed(ex) from ex
homeassistant.helpers.update_coordinator.UpdateFailed: ('[Errno 104] Connection reset by peer', None)
```

**Comment by Vaskivskyi** [comment]
Ok. New error, even though similar. Will continue to work on this

**Comment by pumpan** [comment]
i had the same problem, i got it fixed when i 1. removed the integration, 2. restarted home assistant 3. installed again 4. restarted again.

**Comment by Vaskivskyi** [comment]
Hey @pumpan,

Thanks for your feedback! :+1:

Unfortunately, this might be only a temporary solution. The `connection reset by peer` is device-related, not integration-related. This is great, it has solved the problem for you. But, maybe, it was a happy coincidence.

**Comment by bernardovalente** [comment]
After updating to 2022.10.x there are no errors popping up and all the devices and sensors seem to be working with no problems. Really thankfull of your work and community support. Feel free to close this.

Cheers!

**Comment by Vaskivskyi** [comment]
Ok, great. It seems this was one of those HA-related problems. Still don't understand, how this is happening for different users with different integration, that something just stops working and then fixes itself.

If you experience any other bugs, please open a new issue.
