### ISSUE TITLE
[Bug] Device trackers are stuck

### ISSUE THREAD

**Issue by Vaskivskyi** [Vaskivskyi/ha-asusrouter#570]
### The problem

Some devices are experiencing problems with device trackers. The symptoms are the following:

- Device trackers might switch to `home`, but never to `away`
- Device trackers might be stuck in any state

**If you are experiencing a similar problem, please add your device MODEL and FIRMWARE VERSION in the comments. Also, add AsusRouter version you are using**

If you see any errors or warnings in the HA log from AsusRouter, please add them as well.

Please, don't post "the same error" without any details about your device. This does not help. In order to find and fix the issue, information is needed.

P.S. All other issues with the same problem will be closed. Please, report this problem here and only

### Your device model

RT-AX88U

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.1

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.3.0

**Comment by Vaskivskyi** [comment]
So, this is the data collected from the other issues. I would kindly ask all the tagged users to check whether the issue with device trackers still persists with the latest version 0.22.0. And then we will try to solve it

---

From #562 (@pejannl):

- RT-AC88U / 3.0.0.4.386_48260

---

From #550 (@alhemicar86):

- TUF-AX5400 / 3.0.0.4.388_22525-gd35b8fe / 0.21.0

---

From #485 (@5a5cha):

- GT-AX11000 / 3.0.0.4.388.1 / 0.17.4, 0.18.0

---

From #465 (@ejpenney):

- RT-AC66U / 3.0.0.4.380.70 / 0.17.4

**Comment by pejannl** [comment]
What can I say to help you?
Running Asus rc-ac88u, Firmware Version:[3.0.0.4.386], standard firmware
Home Assistant core 2023.01.1
Asusrouter integration 0.22.0

I don’t use the wireless on the router, but use a home deco mesh system. I have ping to my iphone (in dhcp fixed ip) installed and also use the deco integration to detect presence of my iphone. I just switched my iphone to airplane mode. Within 2 minutes the ping and deco integrations report I am not home. I waited 15 minutes, but the Asusrouter integration never reports me away. I am aware there some sort of technical log in HA, but don’t know where to find it. If you need to know more then direct me where to look.

**Comment by alhemicar86** [comment]
Updated to 0.22.0, will keep an eye on extension.

**Comment by alhemicar86** [comment]
State updates still get stuck after several hours.

**Comment by alhemicar86** [comment]
0.20.0 actually made it worse in a way that now trackers don't update even after integration is reloaded.

**Comment by khaffner** [comment]
Your device model
RT-AC3200

Firmware type
? Stock Asus firmware

Firmware version
3.0.0.4.382_52651-g22bb56a, is up to date

Integration version with the issue
I've used 0.21.0 and 0.22.0, same issue in both

Method of the integration installation
HACS

What version and type of Home Assistant installation do you use
Container 2023.3.1

Is there anything useful in the logs?
No, looked at the debug logs.

Diagnostics information
No response

Additional information
No response

**Comment by alhemicar86** [comment]
Somehow it decided at random to work now, and I made no changes to it. Will follow up tomorrow if it kept working after nightly router reboot.

**Comment by Vaskivskyi** [comment]
For now, I am trying to collect as much data as possible on the issue. The main problem is, that exactly the same device models with the same FW version work for one user, but not another.

This makes the bug quite hard to locate and troubleshoot

**Comment by alhemicar86** [comment]
If it is any help, my installation is HA OS, on https://www.gigabyte.com/Mini-PcBarebone/GB-BMPD-6005-rev-10#kf

**Comment by pejannl** [comment]
Ack. I am also running HA OS (on a Raspberry PI 4).

**Comment by nickaggie** [comment]
Im seeing the same issue, trackers haven't updated for a while.

Your device model
RT-AX88U

Firmware type
Merlin

Firmware version
388.1

Integration version with the issue
0.22.0

Method of the integration installation
HACS

What version and type of Home Assistant installation do you use
Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest

**Comment by 5a5cha** [comment]
Looks like a really strange behave, so far.

While my S22 is tracked nice when turning of the wifi and change to mobile data the raspberry pi on the other hand is still online after poweroff and unplug from power cable.

The frontend (AiMesh overview) of the router shows the pi online when online and is not listed when offline.


On the other hand i have three 3D printers with mainsail OS running and all three of them are powerless but two of them are listet as online and only one is offline. 

Tracking with laptop is still ongoing because of work :-)


Your device model
GT-AX11000

Firmware type
Merlin

Firmware version
388.1

Integration version with the issue
0.22.0

Method of the integration installation
HACS

What version and type of Home Assistant installation do you use
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0

Is there anything useful in the logs?
No response

Diagnostics information
No response

Additional information
No response

**Comment by alhemicar86** [comment]
Found this in logs today. It has also some reference to Python 3.10, preceding the error itself.

2023-03-07 09:06:41.385 ERROR (MainThread) [custom_components.asusrouter.router] Error connecting to '192.168.###.###' for device update: None

It was preceded by (I do have 2 esp32 boards unpowered and disconnected from network ar the moment, and 3 connected): 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 537, in send_message_await_response_complex
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 536, in send_message_await_response_complex
    async with async_timeout.timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 320, in _keep_alive_loop
    await self._ping()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 645, in _ping
    await self.send_message_await_response(PingRequest(), PingResponse)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 554, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 539, in send_message_await_response_complex
    raise TimeoutAPIError(

**Comment by khaffner** [comment]
Knock on wood, but the device tracking seems to work fine for me the last 5 days

**Comment by contrasenda** [comment]
Same problem here.

RT-AX92U / Stock 3.0.0.4.388_22525
Two aimesh nodes: RT-AC68U / Stock 3.0.0.4.386_51255

Asusrouter 0.22, Home Assistant 2023.3.4

Device tracking works ok for some hours, and then stops updating. I checked the router network map and devices are not connected, but the state is not update in HA.
Reloading the integration makes it work again for some time.  No errors in logs, except for unique ids one.

One strange thing I noticed that happens most of the times (but not always), is that the device is reported not home / home / not home withing minutes after leaving, and by that moment phone is quite far, it's impossible to be connected to home wifi.

![image](https://user-images.githubusercontent.com/67908591/225405472-4aa54fdb-cdf4-410a-884b-499fa42d8626.png)

**Comment by pepe59** [comment]
Same problem here, Router Asus RT-AC68U version fw
3.0.0.4.386_51255

**Comment by marceloaf** [comment]
Same problem. GT-AX6000. Merlin 388.1

**Comment by run1fast** [comment]
Same issue. My status is always home, even when I leave and my phone is not connected.
Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1 - latest

Asus Router: ZenWiFi_XT8.
Firmware Version:[3.0.0.4.388_22525]

**Comment by khaffner** [comment]
A reboot of the router seems to work for me. I have automatic reboot once a week, trackers work fine the first few days. Will try to monitor this pattern.

**Comment by run1fast** [comment]
> A reboot of the router seems to work for me. I have automatic reboot once a week, trackers work fine the first few days after. Will try to monitor this pattern.

Rebooted the router, seems to be working again.  I should have known, The IT Crowd, have you tired turning it off and on again?

**Comment by nickaggie** [comment]
After a reboot of my router it seems to have been working for the past few days.

**Comment by Vaskivskyi** [comment]
Hello, guys.

I am sorry for not replying - there were some matters not allowing me to work on AsusRouter lately. But from now on the work will continue as before.

Thanks for all the reports you have already posted. Even the small details might help with the whole picture of the problem core.

@contrasenda, that's an interesting fact. Actually, all the time testing I was only directly disconnecting the device and never tried going out of range. Maybe, the device FW is processing this differently. I will try to check

**Comment by nchieffo** [comment]
RT-AX86S
Firmware Version:3.0.0.4.388_22525
Asus Router HACS 0.22.0

searching for asus in the logs I see only this

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:559
First occurred: March 29, 2023 at 05:04:34 (2 occurrences)
Last logged: March 31, 2023 at 03:32:11

Updating state for device_tracker.pixel_6a_nc (<class 'custom_components.asusrouter.device_tracker.ARDeviceEntity'>) took 0.695 seconds. Please report it to the custom integration author.
Updating state for device_tracker.sm_r860_4 (<class 'custom_components.asusrouter.device_tracker.ARDeviceEntity'>) took 0.758 seconds. Please report it to the custom integration author.

**Comment by alhemicar86** [comment]
That might be a good clue. Asus routers have under "professional" setting an option to automatically disconnect clients below certain signal power. It is intended for Ai Mesh clients to faster roam between the nodes. It might be indeed an issue, since it might intentionally disconnect the client and don't report it disconnected, as it awaits it to reconnect?
Can we confirm if everyone with an issue has Ai Nodes? (Though this setting might be actually enabled on the single router as well to allow swapping between 5 and 2.4 networks?)

**Comment by pejannl** [comment]
I hope I am not spoiling the joy when I write that all my devices are considered ‘wired’ connections. I have a Deco mesh wifi system in use and all tracked devices connect to the wifi through the Deco system. The Asus router doesn’t have any wifi connected devices. 

the Deco’s recognize when a device is offline (‘not home’) within minutes after departure (or switching off). I am in fact using the Deco integration for home detection (but have the Asusrouter integration installed to help analyzing the problems).

**Comment by Vaskivskyi** [comment]
@pejannl,

So all of your devices are not connected over WiFi to the Asus device? Do they show in the Asus Web UI as wired as well or only in AsusRouter?

**Comment by pejannl** [comment]
The router i/f shows them as wired. I have only my Harmony Hub directly connected to the router and it sows only that device as wireless. I don’t know how to see how Asusrouter shows the difference between wired and wireless.

**Comment by pejannl** [comment]
Then I noticed (see picture above) that Asusrouter reported one of us as absent (iphone.bella). I opened the history and she is away since approx 30 minutes, confirmed by the Deco integration.

So I put my own phone in flight mode and waited a few minutes...

The top panel shows the status as per Deco integration, the bottom shows the Asusrouter... 

![IMG_3558](https://user-images.githubusercontent.com/73560870/229343941-8bd736f3-1412-4d99-a40f-eea3c21394de.jpeg)

**Comment by pejannl** [comment]
Uh... The mystery continues... Actually, Asusrouter reports Bella as absent for less than 30 minutes while the Deco reports her absent for 2 hours!

<img width="542" alt="Scherm­afbeelding 2023-04-02 om 11 24 08" src="https://user-images.githubusercontent.com/73560870/229344257-35b72cf9-03c0-478e-a0b4-1e2c6f794dc5.png">


<img width="533" alt="Scherm­afbeelding 2023-04-02 om 11 23 06" src="https://user-images.githubusercontent.com/73560870/229344283-58dd9962-59b4-4cc9-930b-2f2c21746f6d.png">

**Comment by ejpenney** [comment]
Hi,

Just chiming in here that with the RT-AC66U I'm not seeing a lot of issues.  I have noticed that immediately after rebooting the Home Assistant offline devices go "Unavailable" instead of "away" until they return.  Looks like between boots the integration maybe forgets about previously tracked devices?

In any event, no major complaints from me right now.

**Comment by TeddyLafrite** [comment]
Hi @Vaskivskyi 


Same problem here with model RT-AX55 with firmware 3.0.0.4.386_51598

Since few weeks some devices stuck home

Thanks,

**Comment by auanasgheps** [comment]
I have an issue with device tracker, but I'm not sure is related to this one. I see the entities but they're disabled. #592

**Comment by khaffner** [comment]
> A reboot of the router seems to work for me. I have automatic reboot once a week, trackers work fine the first few days after. Will try to monitor this pattern.

It was in the end not a reliable solution. I've since changed to the nmap integration, that suits my needs and is rock solid.

**Comment by TeddyLafrite** [comment]
> > A reboot of the router seems to work for me. I have automatic reboot once a week, trackers work fine the first few days after. Will try to monitor this pattern.
> 
> It was in the end not a reliable solution. I've since changed to the nmap integration, that suits my needs and is rock solid.

Its seems that rebooting integration solves temporarely the problem

**Comment by pepe59** [comment]
I'm also thinking about another device tracker because the AsusRouter is unusable today.

**Comment by TeddyLafrite** [comment]
> I'm also thinking about another device tracker because the AsusRouter is unusable today.

Hi
Same here...

Maybe it's another bug but phone's status is buggy : 
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/c1fd26e5-5f64-4cf4-a65b-4c645208e71f)

home/not-home every 5 minutes all night long..

**Comment by TeddyLafrite** [comment]
NB : same as #593

**Comment by DaveStLou** [comment]
Model: RT-AX88U
Firmware: Merlin 388.2_2
Integration: 0.22.0

I have been devices that are stuck on home for some time. Reloading the integration corrects the status temporarily.

**Comment by TeddyLafrite** [comment]
Some news here ?

**Comment by run1fast** [comment]
I tried doing some digging on this.....

I have an Asus AX XT8 router and 1 airmesh node.  I dug into my router info (http://router.asus.com/index.asp) and I noticed that one of the devices I was tracking that kept getting stuck in a state was not always showing up in the router device list. I know for 100% sure my phone was connected to wifi, but not in the router device list therefore probably not sending the updated state to this Integration.

I found some Asus threads where others also had issues with devices not showing up in the device list eventhough they were connected. The fix was to create a guest wireless connection (feel free to hide it) for your router. You dont have to connect anything to the guest ssid, but just create it. Then the bug of not all devices showing in Asus device list is fixed. 
Now that all my devices are showing in the router list, the state is being passed to this Integration correctly (and no daily reboots or reloading of the integration are needed).

So if you are having this device stuck state, check within the Asus app or config page (http://router.asus.com/index.asp) and see if your device is actually in the list there. 
This solved my problem so far. Been stable and working for about 1 week now.

**Comment by pejannl** [comment]
> I found some Asus threads where others also had issues with devices not showing up in the device list eventhough they were connected. The fix was to create a guest wireless connection (feel free to hide it) for your router. You dont have to connect anything to the guest ssid, but just create it. Then the bug of not all devices showing in Asus device list is fixed. Now that all my devices are showing in the router list, the state is being passed to this Integration correctly (and no daily reboots or reloading of the integration are needed).

I tried this. I created a guest wifi network. Then I rebooted the router. Now, three days later, my Deco integration reports that one person is home and three are not. (Two Iphones and one Android, if that matters). The Asusrouter "integration" reports all four at home.

The add-on is unusable, so I am removing it and will rely on the perfectly working Deco integration.

Signing-off.

**Comment by run1fast** [comment]
This is back to not working again. I went and setup an automation to reload the integration multiple times a day. Hopefully the reload will be a stop-gap.

**Comment by alhemicar86** [comment]
This might be more widespread issue, even the asuswrt that is included in HA is not tracking properly. Also found out that integration intended to give info about washing machine behaves exactly the same... Stops updating after some amount of time. This might be the issue in HA, hope they are aware of it.

**Comment by auanasgheps** [comment]
In my case, looks like my router (AC-86U) has an extremely unreliable client monitoring.
When I login in the Router UI and load the client list, it immediately updates the tracked devices in HA.

Either this and the official integration show the same behavior in my case, so I think it's the router.

Have you seen the same

**Comment by Vaskivskyi** [comment]
The main issue, as already pointed here, is the fact that some routers themself do not show the connected devices properly.

E.g.,on the RT-AC66U I have partial access to, the devices are only coming online but not offline even in the Web UI. Unless, you manually open the device list menu (via the "full list" button) in the Web UI. Unfortunately, even mimicking this behavior from the integration side, I didn't yet manage to solve the issue.

With some other devices the method of the guest networks does really help, but not all of them.

So, I hope, you can understand, when the issues are on the device side, it's not as easy to be fixed (or even avoided) from the external integration

In any case, the work on fixing at least a part of issues with the device tracking is ongoing. As soon as there will be any news, I'll let you know

P.S. As for the "I'll never use AsusRouter again", I am surely sad of hearing this, but AsusRouter is my hobby project, done by testing on a single device I have available. Please, try to understand this limitations. You can always use the default HA AsusWRT integration which will have quite the same problems. Or, for the devices you need to know exact location, you better use the proper way of monitoring - which is never a router - WiFi connection requires quite some time and you can actually cross all the WiFi coverage area before your device authenticate and the router (of any model and manufacturer) will report it

**Comment by pepe59** [comment]
Your comment is fine, the component is great, but it's strange that previously device tracking (phone) worked without problems on my router RT-AC68U and HA. Even today the devices are correctly detected online/offline in the router only this state fails to load HA.

**Comment by alhemicar86** [comment]
Today I was tackling unrelated bug, it was a problem with rendering the default Overview dashboard, and stumbled upon a thread that pointed out about bug that didn't treat properly entities that had space at the end of the name. I chased down one entity created by another integration that had extra space at the end, and once I fixed that, after the reboot, the trackers started working as intended in both AsusRouter and AsusWRT integrations. I can't confirm yet if that was the culprit, but so far everything seems to work as intended. Will see in a few days.

**Comment by alhemicar86** [comment]
An update: never had an issue since I fixed the naming problem. Just to be clear, it is not the names you can give to an entity, as the HA will prevent you from adding space, but any integration can do it, and as it was my case it affected function of other integrations, without me being able to see the cause, and without anything in logs. So to shorten it, I extracted list of all entities with their names, found the one with extra space using regex search in n++, fixed it and after that two integrations were working flawless. So if stat was a problem with mine, steps to reproduce it would be to use some non GUI method to inject entity with space at the end into the system and it should go haywire from there, and shouldn't show logs.

**Comment by TeddyLafrite** [comment]
Hi

For information :


![ASUS WRT](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/70380e91-5185-4421-a63b-f58a54a4ad33)
![ASUS Router](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/afd9ef33-c9d8-4196-8fac-c941ce085329)

Asus WRT vs Asus Router

Asus WRT = SSH
Asus Router = no SSH

**Comment by TeddyLafrite** [comment]
Asus Router is compeletey inexploitable

**Comment by kramttocs** [comment]
> Asus Router is compeletey inexploitable

Can you explain what you are meaning?

**Comment by Delphius7** [comment]
### Your device model
RT-AX86U

### Firmware type
Merlin

### Firmware version
3.0.0.4.388.2_2

### Integration version with the issue
0.22.0

### Method of the integration installation
HACS

### What version and type of Home Assistant installation do you use
Container 2023.9.2

### Is there anything useful in the logs?
_No response_

### Diagnostics information
_No response_

### Additional information
_No response_

**Comment by gregoriusus** [comment]
@Vaskivskyi Can I buy you a few coffee, if you can solve this issue. This is main feature of this addon.

**Comment by Vaskivskyi** [comment]
@gregoriusus,

I can only wish, this issue could be fixed in such a simple way.

Ongoing work, unfortunately, but I hope to eventually fix it

The main issue is that exactly the same model with the same FW might work for some users and not work for others, which makes everything even more complicated

**Comment by alhemicar86** [comment]
Hey, I set it somehow to work since last time. Left it running and forgot about it. Checked logs now it seems to report accurately. What I did was to login into each mesh node separately (not just router), and to check all three events to track (default is just reporting new connections). Don't know what fixed the problem, but it may be related to a fact that device leaves network when attached ro another node, so the main node doesn't report it, but the node it left does? Not sure that is the case, but it works after configuring it like that.

**Comment by gregoriusus** [comment]
I am also using mesh node. @Vaskivskyi, do you think that could be something because of mesh nodes? How can I enable and see logs? I am that versatile in HA yet.

**Comment by alhemicar86** [comment]
Try manually adding all nodes by their IP addresses, and be sure that they won't change (bind them to node mac addresses in router). Be sure to set integration for each node to report all state changes (not just connections which is default).

**Comment by gregoriusus** [comment]
Just done and suddenly my phone shows event after two days. Will also fix DHCP of node in router. Cross my fingers that this is it 🤞

**Comment by Vaskivskyi** [comment]
That's good if your case was solved this way.

There are several semi-independent parts of the tracking problem:
- AiMesh system which is not updating fully each time, rather by parts
- The main Asus FW issue with not updating entries unless triggered manually
- A bug with leaving the range of WiFi - in that case device does not "disconnect", rather "fade" which does not trigger router to mark it disconnected

Unfortunately, they are only semi-independent and work differently for each use-case

**Comment by gregoriusus** [comment]
@Vaskivskyi, which Asus router do you use? Or anyone, which Asus router do you have that works great with Mesh network?

**Comment by Vaskivskyi** [comment]
@gregoriusus,

I have only a single RT-AX88U, so cannot say a lot about AiMesh. My apartment is not too large, so no need for an additional router.

I temporarily had RT-AX92U for tests when adding AiMesh support, but I had to forcibly connect some devices to this node, otherwise, they would have stayed with the main device. So my experience won't be of a large help

**Comment by gregoriusus** [comment]
Unfortunately, adding node configuration, didn't help. 
Still no reporting of state in 2 days.
I like Asus router, but integration to home assistant is more important. Guess will have to find a router that works with HA flawlessly. 
@Vaskivskyi, your work with integration and for community is amazing.

**Comment by Vaskivskyi** [comment]
The main issue I see with Asus - is tons of legacy. Their API, which is also used by the integration is a Frankenstein's monster of many years of work. This creates lots of complications. Maybe they'll improve it eventually. Or I'll manage to make it all work. We'll see what comes first. But the devices themself are not bad. Also, for an average user, they are quite easy to set up and forget

**Comment by deepansteven** [comment]
When reloading the integration, then it will update the devices correctly in my case. I will now enable this in as reoccurring automation, until the bug is fixed. I also have a mesh network, and adding the node did not help either. I have an Asus RT-AX88U + AC68U (node).
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/59923153/463f32f7-658a-48f8-b729-5b391e3cb9aa)

Direct Link to the service call: https://my.home-assistant.io/redirect/developer_call_service/?service=homeassistant.reload_config_entry

**Comment by gregoriusus** [comment]
@Vaskivskyi, if reload helps, could it be something in code that could solve an issue?

**Comment by deepansteven** [comment]
> @Vaskivskyi, if reload helps, could it be something in code that could solve an issue?

Agree, but could you also confirm that reloading through the UI helps, then we can near it down to code level rather than router or device specific error. In my case the router network page is showing correctly after connect and disconnect.

**Comment by gregoriusus** [comment]
Can someone point me how to reload configuration of AsusRouter?

**Comment by gregoriusus** [comment]
I found out. Yes, at the moment when configuration was reloaded, my phone on wifi got status. @Vaskivskyi, could be something on this 👍

**Comment by kramttocs** [comment]
> When reloading the integration, then it will update the devices correctly in my case. I will now try to enable this as reoccurring automation, until the bug is fixed. I also have a mesh network, and adding the node did not help either. I have an Asus RT-AX88U + AC68U (node). ![image](https://user-images.githubusercontent.com/59923153/275806623-463f32f7-658a-48f8-b729-5b391e3cb9aa.png)
> 
> Direct Link to the service call: https://my.home-assistant.io/redirect/developer_call_service/?service=homeassistant.reload_config_entry
> 
> In any case a restart of home assistant is also solving this is issue, so restart at night until the bug is fixed is another approach.

Been using this approach for awhile myself as a band-aid
https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/576?u=kramttocs

**Comment by deepansteven** [comment]
Ok, the next debugging could be from the other post:  
Remove the node for few days to see if that helps
Reset the router fully and setup from ground up in home-assistant
Only have Merlin firmware on the router and stock firmware on the node

**Comment by Vaskivskyi** [comment]
Hey, guys. I'll look into this.

The only device I saw a problem by myself is an old RT-AC66U - on that one devices are not tracked correctly in the Web UI of the router as well and nothing was changing when the integration is reload

**Comment by deepansteven** [comment]
> Hey, guys. I'll look into this.
> 
> The only device I saw a problem by myself is an old RT-AC66U - on that one devices are not tracked correctly in the Web UI of the router as well and nothing was changing when the integration is reload

@Vaskivskyi : Great to hear. Does it mean you don't need more debugging, and know where in code that has an issue?

**Comment by Vaskivskyi** [comment]
There is a new version of the integration coming soon with a new backend. Hopefully, the issue will be solved already there, since the communication methods were completely changed. But there is still some more work to be done before it's ready

**Comment by gregoriusus** [comment]
If there is a way, I can test it, before you submit. Or I can open you a VPN to my router. I would really like to see that this integration works. Device tracker is most used feature for router integration.

**Comment by Vaskivskyi** [comment]
Hello, guys. If anyone is up to new tries, you can check the latest beta release `0.23.0b1` and let me know if anything changed for you

**Comment by deepansteven** [comment]
Hi @Vaskivskyi , thanks already on it as soon as I saw your beta version 😀. Will let you know in couple of days, as it normally takes 12-24 hours before the issue was showing up and not updating, after a restart.

**Comment by jata1** [comment]
I have installed latest beta and now I have issues with device tracking. device tracking was working correctly before installing the beta. My router is a RT-AX86S running the latest merlin 3004.388.4.

Easy to reproduce as all of the devices that I track are not working correctly anymore. I have updated the integration config to stop tracking, deleted the entities and re-enabled them but I have the same issue. 

Happy to help troubleshoot/debug if helpful so let me know what I can do. See below. This device letf home at 7.30am but continues to update the connected and last activity fields. Other fields remain populated with incorrect data e.g. rssi

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/23280705/8083edfc-dde1-453e-af53-63bf6acdea70)

**Comment by Vaskivskyi** [comment]
@jata1,

Can you please check the `connected_devices` sensor? Does it also show number of the active devices higher than the Web UI of the device?

**Comment by jata1** [comment]
not quite sure what you are asking but I can confirm that all three of the devices I track are reported as connected in the attributes for the connected_devices sensor. Interestingly, these devices are at the very bottom of thee list and have node set to null - see below.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/23280705/1209a291-5ce4-41bb-87b1-f0073b738122)

**Comment by TeddyLafrite** [comment]
Hi there,


I'm testing for 24h the beta 0.23.0b1 and devices tracker seems to work great :

AsusRouter vs AsusWRT :
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/b3035db2-8a21-4e7a-a810-27e9cbcd147f)

As a reminder : ASUS model RT-AX55

I'm installing 0.23.0b3 and will post results here in 2 ou 3 days

**Comment by Vaskivskyi** [comment]
@jata1, please check version `0.23.0b4`

**Comment by jata1** [comment]
Sorry - still not working. Same issue but all three devices were away when I installed the update so not sure if that could impact.

**Comment by Vaskivskyi** [comment]
@jata1, a couple more questions. Does it happen only with Apple devices? If so, let me know the iOS version so I can try to search for a device to reproduce the issue.
Also, does it happen the same when the device leaves the Wifi coverage zone and when you just toggle flight mode in the phone?
I would also need your HomeAssistant version and Python version

**Comment by jata1** [comment]
I have updated to v0.23 from the beta but I still have the same issue. We all have iPhones and I am only interested in tracking them as they are are the family primary device that I use for location based automations (home / away). With v0.22 everything was working fine.

Version info:
Home Assistant 2023.10.5
Frontend 20231005.0 - latest

I am running HA in a docker container - so latest stable release 
image: "ghcr.io/home-assistant/home-assistant:stable"

So the python version will be whatever shipped with this docker image. Just checked this and it is
Python 3.9.2 

Phones are all on ios 16
iphone 11 - ios 16 latest
iphone 11 pro - ios 16 latest
iphone 13 pro - ios 16 latest

From what I can see, these devices are all doing the same thing. When off my network whether wifi off or out of range the devices still think they are connected both at the device tracker entity and the connected_devices entity.

I can see that the connected attribute on the device tracker is updated when a device joins the network but is not cleared when it leaves and the last activity attribute continues to update even when the device is not on the network.

Hope this helps and you can fix this issue for me as all my location based automations are not working anymore...

**Comment by Vaskivskyi** [comment]
@jata1, I think we found the problem. Your installation still uses Python 3.9, which is not supported by Home Assistant already. It was actually dropped in [2023.2.0](https://www.home-assistant.io/blog/2023/02/01/release-20232/#breaking-changes). With HA [2023.8.0](https://www.home-assistant.io/blog/2023/08/02/release-20238/#breaking-changes) support for Python 3.10 was also dropped and HA Core requires Python 3.11 since then. The same is for the latest release of the AsusRouter backend library. That means, the backend was not updating when you installed any of the `0.23.0` beta or stable releases. Probably, this is the reason for at least part of the issues you are experiencing

**Comment by jata1** [comment]
but python version is bundled in the official HA docker image

**Comment by jata1** [comment]
how can I change this and if it is the problem then everyone using HA docker will be in trouble as it is using the wrong version of python...

**Comment by jata1** [comment]
however - great news we are getting to the issue. I am wondering if any other users of this integration that also use docker can help test/validate...

**Comment by jata1** [comment]
I'm so sorry - I gave you bad information. I just check again and the version of python for the HA docker is

Python 3.11.6

**Comment by Vaskivskyi** [comment]
Ok, good, then I would need to test this. I will try to get access to a device with iOS in the following days to reproduce the issue. I'll keep you informed

**Comment by jata1** [comment]
Thanks and apologies again for giving you the wrong info earlier. Let me know if I can help test anything.

**Comment by jata1** [comment]
Not sure if this helps but one thing i see with the devices that are not working correctly is they do not have a attribute for node when they are off the wifi - see below. I will check when they come back on the wifi to see if the node attribute returns.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/23280705/17431eb7-1f4b-4bd8-8e51-3eee307168f5)

**Comment by TeddyLafrite** [comment]
Hi,

Results for 0.23.0b3 version : devices trackers is OK !

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/87827af9-f06d-4c3d-bcf8-e01a7ac9e3b0)

Installing 0.23.0b4 and HA Core 2023.11.0 !

**Comment by jata1** [comment]
@Vaskivskyi - I can confirm that when the tracked devices are on the network then the node attribute is included in the connected_devices entity. I hope this is a clue/lead.

**Comment by gregoriusus** [comment]
I think it is better, but still not perfect. 

In screenshot, you can see attributes have correct information, but log doesn't show correct information. Laptop was off whole day, but it had status home. Attributes show correct connected time. So it should be set from Away to Home at the time shows in attributes.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/4267743/9add4fb4-6f31-4c39-81e3-5abf544afba7)

**Comment by TeddyLafrite** [comment]
Hi,

Seems to have problems with another HA installation - exactly same as mine : ASUS RT AX-55 + Rpi4

Delay home/not_home is not exact : 
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/37acd1c1-93a3-44e6-b885-3c8977805fc5)

Latest_connected sensor is buggy : 
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/7fb3af1c-0709-4a11-a279-d80774188fb0)


I have no problem with my first HA installation.
Will desinstall/reinstall AsusRouter and check

**Comment by jata1** [comment]
@Vaskivskyi - I have another clue. I rebooted my router and it looks like connected devices are behaving correctly. I didn't think to reboot the router as part of previous troubleshooting. 

Maybe the back-end changes in the integration needed the router to be rebooted to work properly?

**Comment by gregoriusus** [comment]
@Vaskivskyi, I installed latest version and it still has issue with tracking devices after some time. Then I installed ASUSWRT and it tracks devices correctly. I thought that Merlin firmware and additional node was the problem. But ASUSWRT has no problem with tracking. Can I have both components installed side by side to compare it?  I think that ASUSWRT tracks via SSH?

**Comment by Vaskivskyi** [comment]
@jata1, that would be weird. There is no dependency on the router state. So it can only be an issue if your device was keeping too much data in the cache (or if the data was corrupted) - both those cases would be fixed with a reboot. And both can happen with time, since Asus is not too great with memory management

@gregoriusus, you can use AsusWRT in SSH or Telnet without any interference with AsusRouter

**Comment by jata1** [comment]
Nothing changed on my system except for a reboot of the router. My router had been working great for weeks with earlier versions of the integration but something got screwed up with the back-end update and/or something on the router. 

Seems to be working fine now but I will update here if i see it happen again. Thanks again for all your work @Vaskivskyi on this integration

**Comment by TeddyLafrite** [comment]
Hi,
There is another error with trancking : 
After disconnecting, AsusRouter is giving a false positive 
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/60928a88-f483-4022-8bdf-816836029b52)

**Comment by gregoriusus** [comment]
Latest version has still device trucker stucked. Asuswrt reports correctly.

**Comment by Dejcman** [comment]
Same problem for me on Asus GS-AX5400.

**Comment by fmonday** [comment]
Same issues on a GT-6: mainly never leaving home once there. I have the same issues in ASUSWRT. 
As per what @jata1 said, my problem is tracking iPhones (currently iOS 17.0.3)
Both the router and the node are on 3.0.0.4.388_23145-gaa59a08.
AsusRouter: v 0.23.7
HA Supervised/Debian Bookworm in UTM on an M2 Mac Mini (latest everything)
Python 3.11.2
Home Assistant: core 2023.11.2, supervisor 2023.11.3

**Comment by jata1** [comment]
> Same issues on a GT-6: mainly never leaving home once there. I have the same issues in ASUSWRT. As per what @jata1 said, my problem is tracking iPhones (currently iOS 17.0.3) Both the router and the node are on 3.0.0.4.388_23145-gaa59a08. AsusRouter: v 0.23.7 HA Supervised/Debian Bookworm in UTM on an M2 Mac Mini (latest everything) Python 3.11.2 Home Assistant: core 2023.11.2, supervisor 2023.11.3

I simply rebooted the router and then restarted HA and it has been working perfectly for me. Worth a try if you have not yet tried this

**Comment by fmonday** [comment]
> rebooted the router and then restarted HA

This seems to work for a while for me but then the issue comes back. Right now it's keeping track of one iPhone but not another, which is bizarre. 
For anyone that finds this who is also using iPhones, make sure that the "Private Wifi Address" function is turned off or your phone will use fake MAC addresses and the router won't identify it correctly.

**Comment by jata1** [comment]
shoot. that is a bummer and this is a strange issue for sure. Do you notice that all of the devices that are not working correctly are at the bottom of the connected_devices attributes list without an entry for node?

**Comment by fmonday** [comment]
Yes that's correct- but for some reason I see quite a few that are currently connected that don't have a node listed

**Comment by jata1** [comment]
all my devices have node populated so I am convinced this has something to do with the issue. I have aimesh nodes in my setup too so this could be in the mix as part of the issue... 

Sorry I can't help further.

**Comment by jata1** [comment]
have you tried running merlin firmware on the router and node(s). Unlikely to help as aimesh is all closed source but might be worth a try. Merlin's firmware is way better than stock in my opinion anyway.

**Comment by ageev** [comment]
**Your device model**
RT-AX86U

**Firmware type**
Merlin

Firmware version
3.0.0.4.388.4

Integration version with the issue
0.23.7

Method of the integration installation
HACS

What version and type of Home Assistant installation do you use
Core 2023.11.2

**Comment by Patneys** [comment]
Posted on Nov 20, 2023

Device model
Asus RT-AC86U

Firmware type
Stock

Firmware version
3.0.0.4.386_51915

Integration version with the issue
0.24.0

Method of the integration installation
HACS

What version and type of Home Assistant installation do you use
Core
2023.11.2

Is there anything useful in the logs?
No response

Diagnostics information
No response

Additional information
I am facing the same issue that the device tracker entities in Asus for example phones when not in Wi-fi are still reported to be at 'home'

**Comment by Vaskivskyi** [comment]
Those who want can try the new beta `0.25.0b0` release, implementing PR #718 which should solve the issue of devices being stuck `home`.

The principle is the following, if the option is set (the default is True), before each client poll, AsusRouter will send the update request (the same way Web UI does when you have the right-hand client list open). After a `wait-time` which you can also set in settings (default 3 s) the clients will be polled.

You can always disable clients update forcing or adjust the time to the one that works the best for you.

P.S. The stable integration version `0.25.0` with the same new feature will be released in a couple of days if no new bugs are found

**Comment by Dejcman** [comment]
Still not working for me. Here is a comparison between ASUSWRT and AsusRouter integration.

![snipp](https://github.com/Vaskivskyi/ha-asusrouter/assets/97125442/6067971b-3b7f-47b1-99d5-35451801d15b)

**Comment by Vaskivskyi** [comment]
@Dejcman, please provide the FW version of your device (or the integration diagnostics) and the debug log for the integration for a single clients poll. Example of how it looks:

```
2023-11-24 10:44:45.435 DEBUG (MainThread) [custom_components.asusrouter.router] Device tracking is enabled
2023-11-24 10:44:45.435 DEBUG (MainThread) [custom_components.asusrouter.router] Updating AsusRouter device list for '192.168.1.1'
2023-11-24 10:44:45.435 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_state
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Forcing clients update
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_set_state
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Setting state `AsusSystem.UPDATE_CLIENTS` with arguments `None`. Expecting modify: `False`
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _async_check_state_dependency
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_run_service
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_command: EndpointControl.COMMAND | {'action_mode': 'update_client_list'}
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: EndpointControl.COMMAND
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: EndpointControl.COMMAND | {'action_mode': 'update_client_list'}
2023-11-24 10:44:45.436 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.1.1
2023-11-24 10:44:45.538 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from EndpointControl.COMMAND
2023-11-24 10:44:45.539 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint EndpointControl.COMMAND
2023-11-24 10:44:45.539 DEBUG (MainThread) [asusrouter.modules.service] Service `None` run with arguments `{'action_mode': 'update_client_list'}`. Result: `{}`
2023-11-24 10:44:45.540 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_state
2023-11-24 10:44:45.540 DEBUG (MainThread) [asusrouter.asusrouter] Saving state `AsusSystem.UPDATE_CLIENTS` for `None` s with id=`None`
2023-11-24 10:44:45.540 DEBUG (MainThread) [asusrouter.asusrouter] Waiting for clients to be updated: 3.0 s
2023-11-24 10:44:48.542 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _where_to_get_data
2023-11-24 10:44:48.542 DEBUG (MainThread) [asusrouter.asusrouter] Endpoints to check: [<Endpoint.ONBOARDING: 'ajax_onboarding.asp'>, <Endpoint.UPDATE_CLIENTS: 'update_clients.asp'>]
2023-11-24 10:44:48.543 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-24 10:44:48.543 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING |
2023-11-24 10:44:48.543 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.1.1
2023-11-24 10:44:48.697 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from Endpoint.ONBOARDING
2023-11-24 10:44:48.698 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint Endpoint.ONBOARDING
2023-11-24 10:44:48.698 DEBUG (MainThread) [asusrouter.modules.endpoint] Processing data from endpoint Endpoint.ONBOARDING
2023-11-24 10:44:48.699 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.UPDATE_CLIENTS
2023-11-24 10:44:48.699 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.UPDATE_CLIENTS |
2023-11-24 10:44:48.699 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.1.1
2023-11-24 10:44:48.841 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from Endpoint.UPDATE_CLIENTS
2023-11-24 10:44:48.841 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint Endpoint.UPDATE_CLIENTS
2023-11-24 10:44:48.842 DEBUG (MainThread) [asusrouter.modules.endpoint.update_clients] Reading modern update clients data
2023-11-24 10:44:48.844 DEBUG (MainThread) [asusrouter.modules.endpoint] Processing data from endpoint Endpoint.UPDATE_CLIENTS
2023-11-24 10:44:48.850 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _transform_data for `AsusData.AIMESH`
2023-11-24 10:44:48.850 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _transform_data for `AsusData.CLIENTS`
2023-11-24 10:44:48.850 DEBUG (MainThread) [asusrouter.asusrouter] Transforming clients data
2023-11-24 10:44:48.864 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_flags
2023-11-24 10:44:48.864 DEBUG (MainThread) [asusrouter.asusrouter] Returning data for `AsusData.CLIENTS` with object type `<class 'dict'>`
2023-11-24 10:44:48.879 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching devices data in 0.000 seconds (success: True)
```

You can find the part which we need by searching for `AsusSystem.UPDATE_CLIENTS`

If you don't want to share the data here (especially in case of sharing the full log and not just a part of it), you can send it to me at Yevhenii@Vaskivskyi.com

**Comment by fmonday** [comment]
I tried factory resetting my router and recovering settings but it didn't change anything; the "Last activity" line reflects the current time even when the device is offline. The router is incorrectly reporting that status of the device. 
<img width="542" alt="Screenshot 2023-11-26 at 2 52 11 PM" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/43834799/16556a9c-cdd3-4935-90ff-513be1334395">

There's this, however- the RSSI attribute drops to zero, so I'm just going to write an automation off of that for the time being.

**Comment by 5a5cha** [comment]
Did some tests with iOS and privat MAC.
This function is a piece of sh** when it comes to device tracking. Exactly this tracking is something apple tried to prevent with this function. The tracking only works till iOS generate a new fake MAC.
So maybe this should be mentioned in the manual, @Vaskivskyi?

One important thing to know.
After disable the fake MAC in the iPhone/iPad the "fake" MAC-device stays online in the Integration.


@fmonday, is your source set correctly in the screenshot above?
While i was testing the face MAC i recognized the Source of all my devices is set to "Router".
This is not correct since three devices are connected with cable to the Mesh Node. 
Listed in the WebUI correct at the Node. But in the HA they are shown with Source = Router.
Same for WLAN devices. Some of them are listed in the WebUI connected to the Node. But the Integration lists all @ Router.

**Comment by fmonday** [comment]
> So maybe this should be mentioned in the manual

This is a good point as that feature is enabled by default. That's not the problem we're facing here though. I think that at least in my case it's the router's firmware: I turned off the wifi on my phone for nine hours yesterday but the router GUI still showed it as connected. I've never noticed that behavior before so it must be a bug with the current firmware. This also explains why I'm seeing the same thing with both of the Asus integrations and why `0.25.0b0` didn't work for me. I shiver at the prospect of trying to talk to Asus support about this...

As for nodes: the GT6 does come with a separate node, and I have mine set up using one of the 5Ghz channels for backhaul. I enabled a few clients bound to it and I do see "Router" as the source, but where it says "Node" it has the MAC of the node, not the router itself. That kind of makes sense to me bcz wouldn't the router just be passing information through the node?

**Comment by Vaskivskyi** [comment]
Hello

Yes, the private MAC address on both iOS and some Androids will mess up with the integration by creating several entries. Unfortunately, this cannot be fixed anyhow from the integration point of view. But I will add the possibility to remove trackers as well as some other client-tracking-related features soon.

The integration cannot delete any tracker automatically, because it does not know which devices are real and which are artifacts of the WiFi privacy settings of the clients. I will add info on this to the manual.

As per the `source` in the device trackers - this is something to be compatible with HA - this is one of the [pre-defined types](https://github.com/home-assistant/core/blob/dev/homeassistant/components/device_tracker/const.py#L25): `router`, `gps`, `bluetooth` or `bluetooth_le`. Moreover, this field is required and I cannot remove it.

For AsusRouter the important value in the `node` attribute - this one should show the MAC of the AiMesh node. And (if it works correctly) should explain the best for exactly the device is connected.

---

Unfortunately, proper client tracking is not something straight-forward to implement, because some devices have trouble displaying currently connected devices even in the Web UI - that's from where the fix from `0.25.0b0` comes from. But seems that it's not any universal fix

**Comment by jata1** [comment]
just to chip in, I noticed today that one of my tracked devices is saying its home when its not - it had been working fine for the last couple of weeks but I have updated to the latest beta of the integration.

I have a list view built off connected devices that strips out any clients that do not have an ip address or node. This view is always correct so i'm thinking that it might be possible to do something where the integration does something similar - tests for ip address and node. If both are empty then device is away (if it is tracked). 

Thoughts @Vaskivskyi ?

**Comment by jata1** [comment]
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/23280705/ea4306a4-a2c6-4919-9385-4fd0a523b99b)

**Comment by Vaskivskyi** [comment]
@jata1, if IP is static, the device will have it even when offline

Currently, the backend checks whether the node is present to mark a device as online, but not reverse. This is because older devices might not have AiMesh support at all.

But I can think of something to consider them separately

**Comment by jata1** [comment]
Thanks. This is a great integration and this issue must be driving you mad. All your good work is 100% appreciated

**Comment by jata1** [comment]
@Vaskivskyi - after router and HA restart I still have a client (iphone) not tracking correctly but the attribute data looks good. See below. You can see the client is disconnected but reporting that it is home. Hopefully this is an easy issue to identify/fix.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/23280705/c1813335-2996-4931-be3e-46ccb0c82c05)

**Comment by fmonday** [comment]
> have you tried running merlin firmware on the router

I absolutely would take this advice but I have a GT6 (AX10000) and Merlin doesn't support it yet. As I was looking around in the router's GUI I realized that there was all sorts of weirdness- like multiple devices that have neither the password nor the ability showing as connected to the 5.9 GHz backhaul SSID- so I factory reset and this time did NOT restore from a config file but instead spent hours setting the router up from scratch. The weirdness in the GUI is fixed, but both iPhones are still always home. One of them actually has "Connection type: disconnected" in the attributes. 

Has anyone who is not on Merlin tried talking to Asus?

**Comment by 5a5cha** [comment]
@fmonday, in the early days of my AX11000 I've talked to asus support regarding some issues with one of the external antennas and some bugs in the ROG firmware.
The only thing solved was the broken antenna. The firmware issue ticket came back with some default answer.
But report your issue to asus couldn't be wrong.

@TeddyLafrite, what are your refresh time settings? Are they the same in both integrations? Depending on your timings in the config some delay is normal.

**Comment by TeddyLafrite** [comment]
Hi @5a5cha,
Refresh delay is 15 seconds for both integrations

**Comment by 5a5cha** [comment]
@TeddyLafrite  Ok, that's weird. 

@Vaskivskyi, maybe i got another hint regarding this strange behavior...
I double checked my configuration. Especially my usage type (Router and AIMesh Node) and Interfaces.
At the Router i configured the following interfaces to be tracked:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/5db96e90-21fc-4476-a1e0-bd96a9d9beb8)

The AIMesh Node was 100% configured without the WAN and Bridge interface. But as i checkt it some minutes ago i got the following config:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/b0338660-0f22-4ede-bc97-be7c11041419)
 
After finding myself confused i uncheckt the WAN and Bridge interface at the AIMesh Node again and saved the config. Checked it again and the Bridge was automatically checkt to track again.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/81f3d552-1aa6-463e-9574-49063e6a4044)

**Comment by TeddyLafrite** [comment]
@5a5cha 
@Vaskivskyi 
Last days, delay is sometimes above 30 minutes between AsusRouter & WRT integrations !!

**Comment by Vaskivskyi** [comment]
@5a5cha, yes. Unfortunately, there is still an issue with the data mix between several devices. I hope to be able to solve it soon

@TeddyLafrite, I am working on the device tracking issues

**Comment by Vaskivskyi** [comment]
Version `0.26.0` might help some of you with the device tracking issue. It also fixes AiMesh nodes being reported as clients

**Comment by TeddyLafrite** [comment]
Hi @Vaskivskyi 
Installing and tell you next days
Thanks and happy Christmas :)

**Comment by TeddyLafrite** [comment]
Dear @Vaskivskyi,
Tracker is broken since 0.26.0 version.
Smartphones stucks not_home

**Comment by Vaskivskyi** [comment]
@TeddyLafrite, do you have an AiMesh setup or a single device?

In both cases, please check whether the integration `Connected devices` sensor is showing the same number as the Web UI

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/cbbff1a7-ee00-4f4c-9813-f874f6c0fe5b)

**Comment by TeddyLafrite** [comment]
Only single device, no AiMesh setup

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/ebff14bc-668e-449b-90e8-862774dd70f5)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/280b15cc-dde6-433c-a577-9ec8833078e5)

**Comment by Vaskivskyi** [comment]
Do you use Smart Connect? The feature to route clients automatically between 2.4 Ghz and 5 GHz. If so, you can try disabling it for some time and check

**Comment by TeddyLafrite** [comment]
Yes SmartConnect is active ; i'll disable it and will check

**Comment by TeddyLafrite** [comment]
Tested without SmartConnect : nothing change
Will check again tomorrow

**Comment by TeddyLafrite** [comment]
Confirm
Same problem without smartconnect
Devices are stuck for hours 
Latest version was better

**Comment by ecto1a2003** [comment]
Hello all still seeing issue, latest and greatest for everything. Can provide more info if needed

**Comment by VincentClement1** [comment]
This error is appearing in my logs. If I Restart Wireless through the integration, device trackers are updated and correctly show their home/away status.

Logger: custom_components.asusrouter.router
Source: custom_components/asusrouter/router.py:420
Integration: AsusRouter (documentation, issues)
First occurred: 27 December 2023 at 2:20:49 pm (21 occurrences)
Last logged: 1:52:18 pm

Cannot get clients from '192.168.50.1': ('Cannot connect to 192.168.50.1. Failed in `_send_request`', None)
Cannot get clients from '192.168.50.1': ('No session available for this connection', None)

**Comment by ppmg77** [comment]
**Your device model**
RT-AX88U

**Firmware type**
Merlin

**Firmware version**
388.5

**Integration version with the issue**
0.26.0

**Method of the integration installation**
HACS

**What version and type of Home Assistant installation do you use**
Home Assistant Core v2023.12.4

**Information of the logs**
No related info I could find in the logs.
I did do a reboot of my router a couple of times, which I think resulted in the following messages:

2023-12-28 21:19:50.973 ERROR (MainThread) [custom_components.asusrouter.router] Cannot get clients from '192.168.XX.1': ('Cannot connect to 192.168.XX.1. Failed in `_send_request`', None)
2023-12-28 22:20:41.141 ERROR (MainThread) [custom_components.asusrouter.router] Cannot get clients from '192.168.XX.1': ('Cannot connect to 192.168.XX.1. Failed in `_send_request`', None)

**Additional info**
Also, in the state of the device tracker of my iPhone, I saw that the attribute "Node", does change within seconds of changing the connection state of the iPhone.
iPhone connected to WiFi: "Node: Mac-Address of Router"
iPhone disconnected from WiFi: "Node: Mac-Address of Router disappears"

I hope the above info helps a bit solving the issue. Let me know should more info be needed.

**Comment by 5a5cha** [comment]
Device tracker in 0.26.0 seems to be broken again.

Worked fine in 0.24.2.

Used the update feature within HASC to update from 0.24.2 directly to 0.26.0.
After first issues with device tracking I did a complete uninstall, reboot and fresh install of 0.26.0 with no luck.

**Comment by Vaskivskyi** [comment]
Please, update to `0.27.0` which is already available through HACS

**Comment by TeddyLafrite** [comment]
Hi @Vaskivskyi 
Installed this morning
Tracker seems to work properly

**Comment by Dejcman** [comment]
Hi, 
with the latest update tracker seems to work for me to.

**Comment by jata1** [comment]
@Vaskivskyi - as always thanks for the work you are doing. Latest release 0.27.1 seems a lot better but there is something weird with this integration and the actual router GUI / connected clients views.

In summary, when I have the integration installed. I see some clients in the Asus GUI that are not really connected to the network. I see others that are on the network but reporting as being on the wrong node.

So there is something strange happening and it doesn't surprise me that there ends up being strange behaviour for the connected_devices entity in HA.

I rebuilt my entire Asus network manually on merlin 388.5 and then upgraded to 388.6 alpha but I still have the same issue. the only solution for me has been to remove the integration from HA and reboot the router

**Comment by ppmg77** [comment]
@Vaskivskyi - Installed the latest update and all is working here at the moment. Haven't tested everything yet, but bugs found I'll let it know here.

**Comment by ppmg77** [comment]
> @Vaskivskyi - as always thanks for the work you are doing. Latest release 0.27.1 seems a lot better but there is something weird with this integration and the actual router GUI / connected clients views.
> 
> In summary, when I have the integration installed. I see some clients in the Asus GUI that are not really connected to the network. I see others that are on the network but reporting as being on the wrong node.
> 
> So there is something strange happening and it doesn't surprise me that there ends up being strange behaviour for the connected_devices entity in HA.
> 
> I rebuilt my entire Asus network manually on merlin 388.5 and then upgraded to 388.6 alpha but I still have the same issue. the only solution for me has been to remove the integration from HA and reboot the router.
> 
> I have RT-AX86S with 2x RT-AX58U nodes all running merlin 388.6 alpha

Dear @jata1 ,
The "strange behavior" you're experiencing, does this include devices connect the HA through zigbee2MQTT and MOSQUITTO?

@Vaskivskyi 
After the upgrade, zigbee2MQTT is not able to connect to MOSQUITTO. I've checked again the configs of these 2 docker containers but everything seems to be in order.
See following link to Reddit where I've requested some advice/help with some info if it helps:
[https://www.reddit.com/r/ZigBee/comments/18xim5p/zigbee2mqtt_not_connecting_to_mosquitto/](url)

My router is an Asus RT-AX88u, running on Merlin 388.5.

**Comment by jata1** [comment]
@ppmg77 - I have used mqtt in the past for other integrations but not at the moment. I do have a mqtt/mosquitto container on my system but it is not running.

My issue / strange behaviour is with client trackers with the asusrouter integration. The problem is 2-way in that when I use the asusrouter integration then I see incorrect client data in the asus web gui and I get issues with tracked devices saying they are home when they are away and this is somewhat correlated with that I see in the asus gui.

At the moment, I have completely removed the asusrouter integration from HA and I am now monitoring how the asus gui behaves - so far it is working perfectly so I think the root issue is something to do with the HA asusrouter integration/api

**Comment by ppmg77** [comment]
@Vaskivskyi  @jata1 
I've solved my problem.

I'm running everything in docker containers. Yesterday afternoon zigbee2mqtt was updated from version 1.34.0 to version 1.35.0. This broke the connection between z2m and MQTT broker. I've reverted back to version 1.34.0 and all works smoothly again.

**Comment by Vaskivskyi** [comment]
@jata1,

In case AsusRouter is actually causing troubles with the clients updates in the GUI, try disabling the `force clients update` option and check again, so that we can try locating the issue. Also, please, check the router logs with and without the integration running. In case there are any errors or anything strange in the log, this might be important.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/8cf35530-be45-4b90-884a-c0a96c3b2eff)

In any case, with any of your findings, let's move to a new issue. Interference with the device itself should not be hidden in 100 comments.

---

@ppmg77, good, that your issue was solved. AsusRouter cannot interfere with the network traffic of the device directly. And if so, it would not influence only one connection. MQTT is not any special and is sent via TCP/IP, so troubles in this from the router would also cause lots of other troubles for your network

**Comment by jata1** [comment]
@Vaskivskyi - Understood. I will start a new issue here on github. Maybe easier to discuss on a discord channel/thread

**Comment by TeddyLafrite** [comment]
Hi @Vaskivskyi 
Device trackers with 0.28 is broken again 
Works fine with 0.27

**Comment by Vaskivskyi** [comment]
Since the issue is not only router-related, but client-related, please refer to the issue https://github.com/Vaskivskyi/ha-asusrouter/issues/792 in case you are experiencing troubles after updating to `0.29.0`.

Make sure you are providing all the info as mentioned in the first message of issue #792 - which includes not only router info, but also info on the connection method (including any switch and AP in-between) as well as client info. The first report there is a good example of what to provide.

Don't forget to refer to the section `Total # of devices and connected clients` in the issue description to make sure the issue is actually with the integration and not the "feature" of the FW for your device.

This issue will be closed.
